### ISSUE TITLE
Xbox not turned ON

### ISSUE THREAD

**Issue by Stetocasa** [grzegorz914/homebridge-xbox-tv#118]
After followed with success the authentication, I can turn off the Xbox but cannot turn on!
No errors in the log, find below log and config 

````

"devices":
"name" : "Xbox"
"host":"192.168.1.5"
"xboxliveid":"xxxxxxxxxxxx"
"xboxWebApiToken":
"M.cxxxxxxxxx-939e-ed98"
"refreshInterval": 5,
"disableLogInfo": false,
"webApiControl": true,
"switchInfoMenu": false,
"rebootControl": false,
"recordGameDvr" : false,
"getInputsFromDevice": false,
"filterGames": false,
"filterApps": false,
"filterSystemApps": false,
"filterDlc": false

"platform": "XboxTv"


````

```

09/12/2021, 18:07:14] [XboxTv] Device: 192.168.1.5 Xbox, get Input successful, input: Dashboard, reference: Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application, oneneStoreProductId: Dashboard
[09/12/2021, 18:07:14] [XboxTv] Device: 192.168.1.5 Xbox, get Closed Captions successful: 0
[09/12/2021, 18:07:14] [XboxTv] Device: 192.168.1.5 Xbox, get Current Media state successful: STOP
[09/12/2021, 18:07:14] [XboxTv] Device: 192.168.1.5 Xbox, get Target Media state successful: STOP
[09/12/2021, 18:07:14] [XboxTv] Device: 192.168.1.5 Xbox, get Picture mode: 0
[09/12/2021, 18:07:14] [XboxTv] Device: 192.168.1.5 Xbox, get Mute successful: OFF
[09/12/2021, 18:07:14] [XboxTv] Device: 192.168.1.5 Xbox, get Volume successful: 0
[09/12/2021, 18:07:14] [XboxTv] Device: 192.168.1.5 Xbox, get Power state successful: ON

```

**Comment by adamxfort** [comment]
I'm having the same issue with my Series X. Might be related that there is no "instant power on" setting anymore only "standby". But I do have it enabled.

**Comment by grzegorz914** [comment]
Try 2.0.0 beta Please .

**Comment by Stetocasa** [comment]
> Try 2.0.0 beta Please .

Tried since days but same story

**Comment by Stetocasa** [comment]
> Try 2.0.0 beta Please .

How install from homebridge UI?

**Comment by grzegorz914** [comment]
Just press tools icon and select install other  version

**Comment by Stetocasa** [comment]
> Just press tools icon and select install other  version

![image](https://user-images.githubusercontent.com/70729310/145898510-66377127-64d5-4c09-af0a-b169fb85a652.jpeg)

**Comment by Stetocasa** [comment]
```

          {
                    "name": "Xbox",
                    "host": "192.168.1.5",
                    "xboxLiveId": "FDOODxxxxx26F09F",
                    "clientId": "5e5ead27-xxxxxxxxb3fc-702b28a97404",
                    "xboxWebApiToken": "M.R2_xxxxxxxxxxxx-c3cb-e392-2929-ce2b341c2e4b",
                    "refreshInterval": 5,
                    "disableLogInfo": false,
                    "webApiControl": true,
                    "volumeControl": 0,
                    "switchInfoMenu": false,
                    "getInputsFromDevice": false,
                    "filterGames": false,
                    "filterApps": false,
                    "filterSystemApps": false,
                    "filterDlc": false,
                    "enableDebugMode": false
                }
            ],
            "platform": "XboxTv"

```

**Comment by adamxfort** [comment]
Ok so I got it to work, but for some reason when I turn the xbox off, it will then immediately show up as on again... And in the logs from homebridge it keeps showing as connected. 
![image](https://user-images.githubusercontent.com/32365716/145903664-e3b80fa0-872d-4070-9918-4e6fd58a4e12.png)

**Comment by dennisbekker** [comment]
Same issue, xbox will power off correctly, if i reboot homebridge, status xbox is set to off and i can turn it on again. after powering off again the status off changes to on in the log and the xbox cant be turned on again without a reboot of homebridge

**Comment by dennisbekker** [comment]
solved with the beta version, add live id tested worked. thanks!

**Comment by Stetocasa** [comment]
@grzegorz914 with the beta I not solved the issue. How can we use your plug-in?

**Comment by grzegorz914** [comment]
@Stetocasa 

please enable debug mode in plugin config and get the detailed log, what happened on your side.
