### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by netRunner0** [grzegorz914/homebridge-xbox-tv#20]
![IMG_0761](https://user-images.githubusercontent.com/44049295/81168119-d4c5c100-8faf-11ea-890f-89d6b7e4224c.jpeg)

homebridge-xbox-tv v0.3.14 (inputs or apps)

**Comment by grzegorz914** [comment]
fixed, sorry for that

**Comment by JimmyEyeball** [comment]
Hi I'm still getting this even after the update is it related....



May 06 14:37:52 raspberrypi homebridge[1152]: [5/6/2020, 14:37:52] [XboxTv] Device: 192.168.1.27 LIVINGROOM-XBOX, state: Online
May 06 14:37:52 raspberrypi homebridge[1152]: [5/6/2020, 14:37:52] TypeError: Cannot read property '0' of undefined
May 06 14:37:52 raspberrypi homebridge[1152]:     at xboxTvDevice.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:145:62)
May 06 14:37:52 raspberrypi homebridge[1152]:     at EventEmitter.emit (events.js:228:7)
May 06 14:37:52 raspberrypi homebridge[1152]:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:116:27)
May 06 14:37:52 raspberrypi homebridge[1152]:     at EventEmitter.emit (events.js:223:5)
May 06 14:37:52 raspberrypi homebridge[1152]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
May 06 14:37:52 raspberrypi homebridge[1152]:     at Socket.emit (events.js:223:5)
May 06 14:37:52 raspberrypi homebridge[1152]:     at UDP.onMessage (dgram.js:874:8)
May 06 14:37:53 raspberrypi homebridge[1152]: [5/6/2020, 14:37:53] Got SIGTERM, shutting down Homebridge...
May 06 14:37:53 raspberrypi homebridge[1152]: [5/6/2020, 14:37:53] [XboxTv] Device: 192.168.1.27 LIVINGROOM-XBOX, state: Online
May 06 14:37:53 raspberrypi homebridge[1152]: [5/6/2020, 14:37:53] TypeError: Cannot read property '0' of undefined
May 06 14:37:53 raspberrypi homebridge[1152]:     at xboxTvDevice.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:145:62)
May 06 14:37:53 raspberrypi homebridge[1152]:     at EventEmitter.emit (events.js:228:7)
May 06 14:37:53 raspberrypi homebridge[1152]:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:116:27)
May 06 14:37:53 raspberrypi homebridge[1152]:     at EventEmitter.emit (events.js:223:5)
May 06 14:37:53 raspberrypi homebridge[1152]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
May 06 14:37:53 raspberrypi homebridge[1152]:     at Socket.emit (events.js:223:5)
May 06 14:37:53 raspberrypi homebridge[1152]:     at UDP.onMessage (dgram.js:874:8)
May 06 14:37:53 raspberrypi homebridge[1152]: [5/6/2020, 14:37:53] TypeError: Cannot read property '0' of undefined
May 06 14:37:53 raspberrypi homebridge[1152]:     at xboxTvDevice.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:145:62)
May 06 14:37:53 raspberrypi homebridge[1152]:     at EventEmitter.emit (events.js:228:7)
May 06 14:37:53 raspberrypi homebridge[1152]:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:116:27)
May 06 14:37:53 raspberrypi homebridge[1152]:     at EventEmitter.emit (events.js:223:5)
May 06 14:37:53 raspberrypi homebridge[1152]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
May 06 14:37:53 raspberrypi homebridge[1152]:     at Socket.emit (events.js:223:5)
May 06 14:37:53 raspberrypi homebridge[1152]:     at UDP.onMessage (dgram.js:874:8)
May 06 14:37:58 raspberrypi systemd[1]: homebridgeXbox.service: Main process exited, code=exited, status=143/n/a
May 06 14:37:58 raspberrypi systemd[1]: homebridgeXbox.service: Unit entered failed state.
May 06 14:37:58 raspberrypi systemd[1]: homebridgeXbox.service: Failed with result 'exit-code'.
May 06 14:38:08 raspberrypi systemd[1]: homebridgeXbox.service: Service hold-off time over, scheduling restart.
May 06 14:38:08 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 06 14:38:08 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 06 14:38:11 raspberrypi homebridge[1724]: [5/6/2020, 14:38:11] Loaded config.json with 0 accessories and 1 platforms.
May 06 14:38:11 raspberrypi homebridge[1724]: [5/6/2020, 14:38:11] ---

**Comment by grzegorz914** [comment]
check again

**Comment by emkanie** [comment]
same error here

**Comment by JimmyEyeball** [comment]
0.4.1 Sorry bud looks like I'm still having the same issue...



May 06 19:45:52 raspberrypi homebridge[15785]: [5/6/2020, 19:45:52] TypeError: Cannot read property '0' of undefined
May 06 19:45:52 raspberrypi homebridge[15785]:     at xboxTvDevice.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:145:62)
May 06 19:45:52 raspberrypi homebridge[15785]:     at EventEmitter.emit (events.js:228:7)
May 06 19:45:52 raspberrypi homebridge[15785]:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:116:27)
May 06 19:45:52 raspberrypi homebridge[15785]:     at EventEmitter.emit (events.js:223:5)
May 06 19:45:52 raspberrypi homebridge[15785]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
May 06 19:45:52 raspberrypi homebridge[15785]:     at Socket.emit (events.js:223:5)
May 06 19:45:52 raspberrypi homebridge[15785]:     at UDP.onMessage (dgram.js:874:8)
May 06 19:45:52 raspberrypi homebridge[15785]: [5/6/2020, 19:45:52] Got SIGTERM, shutting down Homebridge...
May 06 19:45:57 raspberrypi systemd[1]: homebridgeXbox.service: Main process exited, code=exited, status=143/n/a
May 06 19:45:57 raspberrypi systemd[1]: homebridgeXbox.service: Unit entered failed state.
May 06 19:45:57 raspberrypi systemd[1]: homebridgeXbox.service: Failed with result 'exit-code'.
May 06 19:46:07 raspberrypi systemd[1]: homebridgeXbox.service: Service hold-off time over, scheduling restart.
May 06 19:46:07 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
May 06 19:46:07 raspberrypi systemd[1]: Started Node.js HomeKit Server.
May 06 19:46:10 raspberrypi homebridge[15921]: [5/6/2020, 19:46:10] Loaded config.json with 0 accessories and 1 platforms.

**Comment by JimmyEyeball** [comment]
May 06 19:49:22 raspberrypi homebridge[16294]: [5/6/2020, 19:49:22] [XboxTv] prepareTelevisionService
May 06 19:49:22 raspberrypi homebridge[16294]: [5/6/2020, 19:49:22] [XboxTv] prepareSpeakerService
May 06 19:49:22 raspberrypi homebridge[16294]: [5/6/2020, 19:49:22] [XboxTv] prepareInputsService
May 06 19:49:22 raspberrypi homebridge[16294]: [5/6/2020, 19:49:22] [XboxTv] Device: 192.168.1.27 LIVINGROOM-XBOX, thisInputs file does not exist
May 06 19:49:22 raspberrypi homebridge[16294]: [5/6/2020, 19:49:22] [XboxTv] Device: 192.168.1.27 LIVINGROOM-XBOX, publishExternalAccessories.
May 06 19:49:22 raspberrypi homebridge[16294]: [5/6/2020, 19:49:22] LIVINGROOM-XBOX is running on port 36089.
May 06 19:49:22 raspberrypi homebridge[16294]: [5/6/2020, 19:49:22] Please add [LIVINGROOM-XBOX] manually in Home app. Setup Code: 999-99-999
May 06 19:49:28 raspberrypi homebridge[16294]: [5/6/2020, 19:49:28] [XboxTv] Device: 192.168.1.27 LIVINGROOM-XBOX, state: Online
May 06 19:49:28 raspberrypi homebridge[16294]: [5/6/2020, 19:49:28] TypeError: Cannot read property '0' of undefined

**Comment by grzegorz914** [comment]
Please get Your config.json

**Comment by JimmyEyeball** [comment]
{
	"bridge": {
		"name": " XBOX",
		"username": "B8:27:EB:FF:EE:55",
		"port": 44455,
		"pin": "999-99-999"
	},

	"description": "XBOX",

	"platforms": [{
		"platform": "XboxTv",
		"devices": [{
			"name": "LIVINGROOM-XBOX",
			"host": "192.168.1.27",
			"xboxliveid": "FD0068E7xxxxxxxxx",
			"volumeControl": false,
			"switchInfoMenu": true,
			"inputs": [{
					"name": "TV",
					"reference": "Microsoft.Xbox.LiveTV_8wekyb3d8bbwe!Microsoft.Xbox.LiveTV.Application"
				},
				{
					"name": "Dashboard",
					"reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application"
				},
				{
					"name": "Spotify",
					"reference": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App"
				},
				{
					"name": "Youtube",
					"reference": "GoogleInc.YouTube_yfg5n0ztvskxp!App"
				},
				{
					"name": "Netflix",
					"reference": "4DF9E0F8.Netflix_mcm4njqhnhss8!App"
				},
				{
					"name": "Airserver",
					"reference": "F3F176BD.53203526D8F6C_p8qzvses5c8me!AirServer"
				}
			]
		}]
	}],
	"accessories": []
}

**Comment by grzegorz914** [comment]
Ok, please update again

**Comment by JimmyEyeball** [comment]
Looking Good.....
